**E-commerce Sales performance Analysis**

In [1]:
import pandas as pd
import numpy as np

In [ ]:
# Load normal CSV files
customers = pd.read_csv("raw_data/olist_customers_dataset.csv")
sellers = pd.read_csv("raw_data/olist_sellers_dataset.csv")
category_translation = pd.read_csv("raw_data/product_category_name_translation.csv")

# Load zipped CSV files
geolocation = pd.read_csv("raw_data/olist_geolocation_dataset.csv.zip", compression="zip")
order_items = pd.read_csv("raw_data/olist_order_items_dataset.csv.zip", compression="zip")
order_payments = pd.read_csv("raw_data/olist_order_payments_dataset.csv.zip", compression="zip")
order_reviews = pd.read_csv("raw_data/olist_order_reviews_dataset.csv.zip", compression="zip")
orders = pd.read_csv("raw_data/olist_orders_dataset.csv.zip", compression="zip")
products = pd.read_csv("raw_data/olist_products_dataset.csv.zip", compression="zip")

**Data Summary**

Brazilian E-Commerce Public Dataset by Olist

 This is a Brazilian ecommerce public dataset of orders made at Olist Store. The dataset has information of 100k orders from 2016 to 2018 made at multiple marketplaces in Brazil. Its features allows viewing an order from multiple dimensions: from order status, price, payment and freight performance to customer location, product attributes and finally reviews written by customers. They also released a geolocation dataset that relates Brazilian zip codes to lat/lng coordinates.


An order might have multiple items.
Each item might be fulfilled by a distinct seller.
All text identifying stores and partners where replaced by the names of Game of Thrones great houses.**

1. Customers Dataset
- This dataset has information about the customer and its location. Use it to identify unique customers in the orders dataset and to find the orders delivery location.

- At this system each order is assigned to a unique customer_id. This means that the same customer will get different ids for different orders. The purpose of having a customer_unique_id on the dataset is to allow you to identify customers that made repurchases at the store. Otherwise you would find that each order had a different customer associated with.

2. Geolocation Dataset
- This dataset has information Brazilian zip codes and its lat/lng coordinates. Use it to plot maps and find distances between sellers and customers.

3. Order Items Dataset
- This dataset includes data about the items purchased within each order

4. Payments Dataset
- This dataset includes data about the orders payment options.

5. Order Reviews Dataset
- This dataset includes data about the reviews made by the customers.

6. Order Dataset
- This is the core dataset. From each order you might find all other information.

7. Products Dataset
- This dataset includes data about the products sold by Olist.

8. Sellers Dataset
- This dataset includes data about the sellers that fulfilled orders made at Olist. Use it to find the seller location and to identify which seller fulfilled each product.

9. Category Name Translation
- Translates the product_category_name to english.

**Description of each columns of the dataset**

Brazilian E-Commerce Public Dataset
1. customers
- customer_id – Unique ID for a customer in a particular order. Each order gets its own customer_id, so the same   person may have multiple customer_ids. Used to connect orders to customers.
- customer_unique_id – Real customer ID that stays the same across all orders made by that person. Crucial for tracking repeat purchases, retention, and loyalty.
- customer_zip_code_prefix – First 5 digits of the customer’s postal code. Helps in mapping customers geographically, calculating distance to sellers, and regional analysis.
- customer_city – The city where the customer lives. Useful for city-level sales, clustering customers, and mapping performance.
- customer_state – Customer’s state abbreviation. Useful for state-level analysis, regional marketing campaigns, and logistics planning.

2. geolocations
- geolocation_zip_code_prefix – Zip code prefix. Links to Customers and Sellers.
- geolocation_lat – Latitude coordinate. Useful for mapping and distance calculation.
- geolocation_lng – Longitude coordinate. Useful for mapping and distance calculation.
- geolocation_city – City name. Useful for regional analysis.
- geolocation_state – State abbreviation. Useful for regional analysis.

3. order items
- order_id – Links the item to a specific order. Unique ID of the order, Think  of it as ONE SHOPPING BILL NUMBER.
- order_item_id – Sequence number of the item within the order. Helps count the number of items per order.
- product_id – ID of the product sold in this item. Links to the Products dataset.
- seller_id – ID of the seller fulfilling this product. Links to the Sellers dataset.
- shipping_limit_date – The latest date the seller can ship the product. Helps track SLA compliance.
- price (R$) – Price of the product. Useful for revenue, profitability, and pricing analysis. Does not include freight.
- freight_value (R$) – Shipping cost for this item. Useful for logistics and cost analysis.

4. order payments
- order_id – Links payment to a specific order.
- payment_sequential – Sequence number if multiple payments were made for the same order.
- payment_type – Method of payment (e.g., credit_card, boleto, voucher, debit_card). Useful for understanding - customer payment preferences.
- payment_installments – Number of installments paid. Shows whether customers prefer installments or full payment.
- payment_value – Amount paid in this payment transaction. Used to calculate total revenue per order.

5. order reviews
- review_id – Unique ID for the review. Primary key for this table
- order_id – The order that this review is about.
- review_score – Rating given by the customer (1 to 5). Key indicator of customer satisfaction.
- review_comment_title – Optional title of the review. Provides short feedback context.
- review_comment_message – Full text of the review. Useful for sentiment analysis.
- review_creation_date – Date when the review was submitted. Helps analyze feedback over time.
- review_answer_timestamp – Date when the seller or platform responded. Helps track response speed.

6. orders
- order_id – Unique identifier for each order. The main key to link all order-related tables.
- customer_id – ID of the customer who placed the order. Links to the Customers dataset.
- order_status – Current status of the order (e.g., delivered, shipped, canceled). Shows fulfillment, delays, and cancellations.
- order_purchase_timestamp – Date and time when the order was placed. Useful for sales trends, time-series analysis, and seasonality.
- order_approved_at – Date and time when payment was approved. Helps track payment processing speed and detect delays.
- order_delivered_carrier_date – Date when the carrier picked up the order. Marks the start of shipping.
- order_delivered_customer_date – Date when the customer actually received the order. Helps calculate delivery times and delays.
- order_estimated_delivery_date – Promised delivery date. Can be used to calculate whether the order was delivered on time or late.

7. products
- product_id – Unique ID of the product. Links to Order Items. Can help to see which product was sold in which order.
- product_category_name – Product category in Portuguese. Can be translated for reporting.
- product_name_lenght – Number of characters in the product name. Helps check completeness of product info.
- product_description_lenght – Number of characters in the product description. Helps check information quality.Can indicate if longer description helps in the growth of e-commerce.
- product_photos_qty – Number of photos uploaded for the product. Indicates quality of product listing.Can indicate if no. of photos helps in more sales
- product_weight_g – Weight of product in grams. Important for shipping cost calculation.
- product_length_cm – Length in cm. Important for shipping dimensions.
- product_height_cm – Height in cm. Important for shipping dimensions.
- product_width_cm – Width in cm. Important for shipping dimensions.

8. sellers
- seller_id – Unique ID of the seller. Links to Order Items.
- seller_zip_code_prefix – Postal code prefix of the seller. Used to calculate delivery distance.
- seller_city – City where the seller is located. Useful for regional performance and logistics analysis.
- seller_state – State where the seller is located. Useful for regional segmentation.

9. category translations
- product_category_name – Original category name in Portuguese.
- product_category_name_english – Translated category name in English. Used for reports and dashboards.

In [5]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB

In [6]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB

In [7]:
orders.value_counts()

order_id                          customer_id                       order_status  order_purchase_timestamp  order_approved_at    order_delivered_carrier_date  order_delivered_customer_date  order_estimated_delivery_date
e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d  delivered     2017-10-02 10:56:33       2017-10-02 11:07:15  2017-10-04 19:55:00           2017-10-10 21:25:13            2017-10-18 00:00:00              1
53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef  delivered     2018-07-24 20:41:37       2018-07-26 03:24:27  2018-07-26 14:31:00           2018-08-07 15:27:45            2018-08-13 00:00:00              1
47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089  delivered     2018-08-08 08:38:49       2018-08-08 08:55:23  2018-08-08 13:50:00           2018-08-17 18:06:29            2018-09-04 00:00:00              1
949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82  delivered     2017-11-18 19:28:06       2017-11-18 19:45:59  2017-11-22 13:39:59           2017-12-02 00:28:42            2017-12-15 00:00:00              1
ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c  delivered     2018-02-13 21:18:39       2018-02-13 22:20:29  2018-02-14 19:46:34           2018-02-16 18:17:02            2018-02-26 00:00:00              1
                                                                                                                                                                                                                              ..
9c5dedf39a927c1b2549525ed64a053c  39bd1228ee8140590ac3aca26f2dfe00  delivered     2017-03-09 09:54:05       2017-03-09 09:54:05  2017-03-10 11:18:03           2017-03-17 15:08:01            2017-03-28 00:00:00              1
63943bddc261676b46f01ca7ac2f7bd8  1fca14ff2861355f6e5f14306ff977a7  delivered     2018-02-06 12:58:58       2018-02-06 13:10:37  2018-02-07 23:22:42           2018-02-28 17:37:56            2018-03-02 00:00:00              1
83c1379a015df1e13d02aae0204711ab  1aa71eb042121263aafbe80c1b562c9c  delivered     2017-08-27 14:46:43       2017-08-27 15:04:16  2017-08-28 20:52:26           2017-09-21 11:24:17            2017-09-27 00:00:00              1
11c177c8e97725db2631073c19f07b62  b331b74b18dc79bcdf6532d51e1637c1  delivered     2018-01-08 21:28:27       2018-01-08 21:36:21  2018-01-12 15:35:03           2018-01-25 23:32:54            2018-02-15 00:00:00              1
66dea50a8b16d9b4dee7af250b4be1a5  edb027a75a1449115f6b43211ae02a24  delivered     2018-03-08 20:57:30       2018-03-09 11:20:28  2018-03-09 22:11:59           2018-03-16 13:08:30            2018-04-03 00:00:00              1
Name: count, Length: 96461, dtype: int64

**Messy data :**

  customer dataset
 - customer_zip_code_prefix(need to reasearch)
 - customer state (need to check about abbreviations)
 - customer cities are written in lower caps
 
  orders dataset
 - date related columns are in string dtype and also time is mentioned in the same column

 geolocations
- customer state (need to check about abbreviations)
- customer cities are written in lower caps(some mismatches are there)
- need to think about the lat/long

 order_items
- Important table 
-  There can be date time issue and datatype issue.

  order_reviews
- need to categorize ratings(1 to 5)
- might be time and date datatype related issue and need to separate time and date column

  orders
- same time and date realated issue in many columns.
- need checking in delivary status column.

  sellers
- seller city and state may contain spelling,abb issue

**Important Notes:**
- ZIP CODE (zip improvement plan) - A number used to identify a specific area for delivering mail(like pin code).
- Boleto - Boleto Bancário (commonly "boleto") is a popular, government-regulated cash-based payment method in Brazil, used for roughly 25% of online transactions. It allows consumers to pay for goods or services using a voucher with a barcode, which can be settled via internet banking, ATMs, or in person at banks, convenience stores, or lottery agents.

**NOTE FOR DATASET**
- need to change codes/prefix coads into a string datatype to avoid calculation or joining errors
- Have a lot of time and date related problems in many tables.
- City names and City state columns need cleaning

**Dirty data :**
- geolocation
- there are duplicate values

- orders 
- misssing values
  - order_approved_at                 160
  - order_delivered_carrier_date     1783
  - order_delivered_customer_date    2965

- order_payments
- there one person with 13664.08 payment_value
- some person paid 0 for order, but more than 1 payment payment_sequential and not defined payment_type 

- order_reviews
- null/missing value in review title and comments
- language issue in reviews

- products
- Sometimes categories have inconsistent naming, and there might be a separate normalized category column called  product_category_name_english
- product category contains some missing values.
- missing values are there

In [8]:
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [9]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [10]:

orders[orders['order_delivered_customer_date'].isnull()]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
6,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,NaN,NaN,2017-05-09 00:00:00
44,ee64d42b8cf066f35eac1cf57de1aa85,caded193e8e47b8362864762a83db3c5,shipped,2018-06-04 16:44:48,2018-06-05 04:31:18,2018-06-05 14:32:00,NaN,2018-06-28 00:00:00
103,0760a852e4e9d89eb77bf631eaaf1c84,d2a79636084590b7465af8ab374a8cf5,invoiced,2018-08-03 17:44:42,2018-08-07 06:15:14,NaN,NaN,2018-08-21 00:00:00
128,15bed8e2fec7fdbadb186b57c46c92f2,f3f0e613e0bdb9c7cee75504f0f90679,processing,2017-09-03 14:22:03,2017-09-03 14:30:09,NaN,NaN,2017-10-03 00:00:00
154,6942b8da583c2f9957e990d028607019,52006a9383bf149a4fb24226b173106f,shipped,2018-01-10 11:33:07,2018-01-11 02:32:30,2018-01-11 19:39:23,NaN,2018-02-07 00:00:00
...,...,...,...,...,...,...,...,...
99283,3a3cddda5a7c27851bd96c3313412840,0b0d6095c5555fe083844281f6b093bb,canceled,2018-08-31 16:13:44,NaN,NaN,NaN,2018-10-01 00:00:00
99313,e9e64a17afa9653aacf2616d94c005b8,b4cd0522e632e481f8eaf766a2646e86,processing,2018-01-05 23:07:24,2018-01-09 07:18:05,NaN,NaN,2018-02-06 00:00:00
99347,a89abace0dcc01eeb267a9660b5ac126,2f0524a7b1b3845a1a57fcf3910c4333,canceled,2018-09-06 18:45:47,NaN,NaN,NaN,2018-09-27 00:00:00
99348,a69ba794cc7deb415c3e15a0a3877e69,726f0894b5becdf952ea537d5266e543,unavailable,2017-08-23 16:28:04,2017-08-28 15:44:47,NaN,NaN,2017-09-15 00:00:00
99415,5fabc81b6322c8443648e1b21a6fef21,32c9df889d41b0ee8309a5efb6855dcb,unavailable,2017-10-10 10:50:03,2017-10-14 18:35:57,NaN,NaN,2017-10-23 00:00:00

In [11]:
order_items.describe()

       order_item_id          price  freight_value
count  112650.000000  112650.000000  112650.000000
mean        1.197834     120.653739      19.990320
std         0.705124     183.633928      15.806405
min         1.000000       0.850000       0.000000
25%         1.000000      39.900000      13.080000
50%         1.000000      74.990000      16.260000
75%         1.000000     134.900000      21.150000
max        21.000000    6735.000000     409.680000

In [12]:
order_items.sort_values(by = 'price', ascending = False).head(10)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
3556,0812eb902a67711a1cb742b3cdaa65ae,1,489ae2aa008f021502940f251d4cce7f,e3b4998c7a498169dc7bce44e6bb6277,2017-02-16 20:37:36,6735.00,194.31
112233,fefacc66af859508bf1a7934eab1e97f,1,69c590f7ffc7bf8db97190b6cb6ed62e,80ceebb4ee9b31afb6c6a916a574a1e2,2018-08-02 04:05:13,6729.00,193.21
107841,f5136e38d1a14a4dbd87dff67da82701,1,1bdf5e6731585cf01aa8169c7028d6ad,ee27a8f15b1dded4d213a468ba4eb391,2017-06-15 02:45:17,6499.00,227.66
74336,a96610ab360d42a2e5335a3998b4718a,1,a6492cc69376c469ab6f61d8f44de961,59417c56835dd8e2e72f91f809cd4092,2017-04-18 13:25:18,4799.00,151.34
11249,199af31afc78c699f0dbf71fb178d4d4,1,c3ed642d592594bb648ff4a04cee2747,59417c56835dd8e2e72f91f809cd4092,2017-05-09 15:50:15,4690.00,74.34
62086,8dbc85d1447242f3b127dda390d56e19,1,259037a6a41845e455183f89c5035f18,c72de06d72748d1a0dfb2125be43ba63,2018-06-28 12:36:36,4590.00,91.78
29193,426a9742b533fc6fed17d1fd6d143d7e,1,a1beef8f3992dbd4cd8726796aa69c53,512d298ac2a96d1931b6bd30aa21f61d,2018-08-16 14:24:28,4399.87,113.45
45843,68101694e5c5dc7330c91e1bbc36214f,1,6cdf8fc1d741c76586d8b6b15e9eef30,ed4acab38528488b65a9a9c603ff024a,2018-04-05 08:27:27,4099.99,75.27
78310,b239ca7cd485940b31882363b52e6674,1,dd113cb02b2af9c8e5787e8f1f0722f6,821fb029fc6e495ca4f08a35d51e53a5,2018-08-02 08:15:14,4059.00,104.51
59137,86c4eab1571921a6a6e248ed312f5a5a,1,6902c1962dd19d540807d0ab8fade5c6,fa1c13f2614d7b5c4749cbc52fecda94,2017-03-23 20:08:04,3999.90,17.01

In [13]:
order_payments.describe()

       payment_sequential  payment_installments  payment_value
count       103886.000000         103886.000000  103886.000000
mean             1.092679              2.853349     154.100380
std              0.706584              2.687051     217.494064
min              1.000000              0.000000       0.000000
25%              1.000000              1.000000      56.790000
50%              1.000000              1.000000     100.000000
75%              1.000000              4.000000     171.837500
max             29.000000             24.000000   13664.080000

In [14]:
order_payments.sort_values(by = 'payment_value', ascending = False).head(10)

,order_id,payment_sequential,payment_type,payment_installments,payment_value
52107,03caa2c082116e1d31e67e9ae3700499,1,credit_card,1,13664.08
34370,736e1922ae60d0d6a89247b851902527,1,boleto,1,7274.88
41419,0812eb902a67711a1cb742b3cdaa65ae,1,credit_card,8,6929.31
49581,fefacc66af859508bf1a7934eab1e97f,1,boleto,1,6922.21
85539,f5136e38d1a14a4dbd87dff67da82701,1,boleto,1,6726.66
62409,2cc9089445046817a7539d90805e6e5a,1,boleto,1,6081.54
43232,a96610ab360d42a2e5335a3998b4718a,1,credit_card,10,4950.34
70320,b4c4b76c642808cbe472a32b86cddc95,1,credit_card,5,4809.44
6440,199af31afc78c699f0dbf71fb178d4d4,1,credit_card,8,4764.34
67546,8dbc85d1447242f3b127dda390d56e19,1,credit_card,8,4681.78

In [15]:
order_payments.sort_values(by = 'payment_value', ascending = True).head(20)

,order_id,payment_sequential,payment_type,payment_installments,payment_value
57411,00b1cb0320190ca0daa2c88b35206009,1,not_defined,1,0.00
100766,b23878b3e8eb4d25a158f57d96331b18,4,voucher,1,0.00
51280,4637ca194b6387e2d538dc89b124b0ee,1,not_defined,1,0.00
36822,fa65dad1b0e818e3ccc5cb0e39231352,14,voucher,1,0.00
77885,fa65dad1b0e818e3ccc5cb0e39231352,13,voucher,1,0.00
19922,8bcbe01d44d147f901cd3192671144db,4,voucher,1,0.00
94427,c8c528189310eaa44a745b8d9d26908b,1,not_defined,1,0.00
62674,45ed6e85398a87c253db47c2d9f48216,3,voucher,1,0.00
43744,6ccb433e00daae1283ccc956189c82ae,4,voucher,1,0.00
17931,0218c7a4fb8d5b1bd22c82b783b8359c,1,credit_card,1,0.01
810,7db5f2eb8f5f54db9f9e71ba4296bcbf,2,voucher,1,0.01
64471,25b5b0ea53b7d5a2d5712a0d9d0b3649,1,credit_card,1,0.01
2522,fb4de3600d359f84927517e78ff9ba54,1,voucher,1,0.01
55432,ca4b9f3ce6fc19e8533501cf8c6b832e,1,credit_card,1,0.01
64178,636f0241ddc83a3b9e37a8088167bd45,2,voucher,1,0.01
11395,4884bd0f5624b0b791920965686cf6ff,1,credit_card,1,0.03
89860,bb1d699eccd1fe0e0b22aea230eab2d0,1,credit_card,1,0.03
56841,2a4cf847d8e23123b4421ef7f7dc3d9f,1,credit_card,1,0.05
49555,d8c4293616878e2f015351d8f1445880,1,credit_card,1,0.05
26330,85a22eb264ad44ff56c4955a66876fed,1,credit_card,1,0.07

In [16]:
df = order_payments[order_payments['payment_value']==0]
print(df)

                                order_id  payment_sequential payment_type  \
19922   8bcbe01d44d147f901cd3192671144db                   4      voucher
36822   fa65dad1b0e818e3ccc5cb0e39231352                  14      voucher
43744   6ccb433e00daae1283ccc956189c82ae                   4      voucher
51280   4637ca194b6387e2d538dc89b124b0ee                   1  not_defined
57411   00b1cb0320190ca0daa2c88b35206009                   1  not_defined
62674   45ed6e85398a87c253db47c2d9f48216                   3      voucher
77885   fa65dad1b0e818e3ccc5cb0e39231352                  13      voucher
94427   c8c528189310eaa44a745b8d9d26908b                   1  not_defined
100766  b23878b3e8eb4d25a158f57d96331b18                   4      voucher

        payment_installments  payment_value
19922                      1            0.0
36822                      1            0.0
43744                      1            0.0
51280                      1            0.0
57411                      1            0.0
62674                      1            0.0
77885                      1            0.0
94427                      1            0.0
100766                     1            0.0

In [17]:
products.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [18]:
sellers.info()

<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: int64(1), str(3)
memory usage: 96.8 KB

In [21]:
order_reviews.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [22]:
order_items['order_id'].duplicated().sum()

13984

In [23]:
order_items['order_item_id'].duplicated().sum()

112629

In [24]:
order_items.duplicated(subset=['order_id', 'order_item_id']).sum()

0